# Generated by Django 6.0.2 on 2026-02-09 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0002_supplier_purchaseline_purchase_supplier'),
        ('sale', '0002_customer_remove_sale_customer_id_remove_sale_user_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('on_hand_qty', models.IntegerField(default=0)),
                ('reserved_qty', models.IntegerField(default=0)),
                ('available_qty', models.IntegerField(default=0)),
                ('last_counted_at', models.DateField(blank=True, null=True)),
                ('created_or_updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('stock_bas', 'Stock Bas'), ('vente_anormale', 'Vente Anormale')], max_length=50)),
                ('severite', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], max_length=20)),
                ('message', models.TextField()),
                ('titre', models.CharField(max_length=255)),
                ('dateAlerte', models.DateTimeField(auto_now_add=True)),
                ('estLue', models.BooleanField(default=False)),
                ('estResolue', models.BooleanField(default=False)),
                ('dateResolution', models.DateField(blank=True, null=True)),
                ('created_or_updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to=settings.AUTH_USER_MODEL)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='stockmouvement.stock')),
            ],
            options={
                'verbose_name': 'Alert',
                'verbose_name_plural': 'Alerts',
                'db_table': 'alert',
                'ordering': ['-dateAlerte'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=20)),
                ('quantite', models.IntegerField()),
                ('reason', models.CharField(blank=True, choices=[('VENTE', 'Vente'), ('ACHAT', 'Achat'), ('INVENTAIRE', 'Inventaire'), ('AUTRE', 'Autre')], max_length=32, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('purchase_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='purchase.purchaseline')),
                ('sale_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sale.saleline')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='stockmouvement.stock')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'stockmovement',
                'ordering': ['-date'],
            },
        ),
    ]
