# Generated by Django 6.0.2 on 2026-04-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmouvement', '0003_alter_alert_stock_alter_alert_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('AJUSTEMENT', 'Ajustement')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('ACHAT_FOURNISSEUR', 'Achat fournisseur'), ('RETOUR_TEST', 'Retour de test'), ('CORRECTION_INVENTAIRE', 'Correction inventaire'), ('CADEAU_PROMO', 'Cadeau/Promotion'), ('VENTE', 'Vente'), ('SORTIE_MAGASIN', 'Sortie magasin'), ('CASSE_PERTE', 'Casse/Perte'), ('ECHANTILLON', 'Echantillon'), ('INVENTAIRE_ANNUEL', 'Inventaire annuel'), ('CORRECTION_MANUELLE', 'Correction manuelle'), ('PEREMPTION', 'Péremption'), ('AUTRE', 'Autre')], max_length=32, null=True),
        ),
    ]
