# Generated by Django 6.0.2 on 2026-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmouvement', '0004_alter_stockmovement_movement_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('critical_stock_threshold', models.IntegerField(default=5)),
                ('notify_low_stock', models.BooleanField(default=True)),
                ('notify_system_updates', models.BooleanField(default=True)),
                ('notify_weekly_report', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
                'db_table': 'systemsettings',
            },
        ),
    ]
