# Generated by Django 6.0.2 on 2026-04-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmouvement', '0006_alter_stockmovement_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(choices=[('stock_bas', 'Stock Bas'), ('vente_anormale', 'Vente Anormale'), ('audit_purge_warning', "Avertissement purge journal d'audit"), ('securite', 'Sécurité')], max_length=50),
        ),
    ]
