# Generated by Django 6.0.2 on 2026-04-17 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_image'),
        ('stockmouvement', '0007_alter_alert_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='product.product'),
        ),
    ]
