# Generated by Django 6.0.2 on 2026-02-07 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ENCOURS', 'En cours'), ('FINI', 'Fini')], default='ENCOURS', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('total_variantes', models.IntegerField(default=0)),
                ('quantite_comptee', models.IntegerField(blank=True, null=True)),
                ('ecart', models.IntegerField(blank=True, help_text='attendu - comptee', null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_counts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Count',
                'verbose_name_plural': 'Inventory Counts',
                'db_table': 'inventorycount',
                'ordering': ['-created_at'],
            },
        ),
    ]
