# Generated by Django 6.0.2 on 2026-02-09 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorycount', '0001_initial'),
        ('product', '0003_remove_product_code_barres_remove_product_code_sku_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expected_qty', models.IntegerField(blank=True, null=True)),
                ('counted_qty', models.IntegerField(blank=True, null=True)),
                ('discrepancy', models.CharField(blank=True, max_length=128, null=True)),
                ('created_or_updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_count', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventorycount.inventorycount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lines', to='product.product')),
            ],
            options={
                'verbose_name': 'Inventory Line',
                'verbose_name_plural': 'Inventory Lines',
                'db_table': 'inventoryline',
            },
        ),
    ]
