# Generated by Django 6.0.2 on 2026-02-09 05:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorycount', '0002_inventoryline'),
        ('product', '0003_remove_product_code_barres_remove_product_code_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_lines', to='product.variant'),
        ),
    ]
