# Backend d'authentification par email
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'user.backends.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]
"""
Django settings for gestion_softcosy project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os

load_dotenv()  # Load environment variables from .env file

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-q=jiv%#!+-6w6u%cc))4((0*^rbmge%qj4i$3^-62k!&8=p7i+')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition
INSTALLED_APPS = [
    'user',
    'product',
    'inventorycount',
    'sale',
    'purchase',
    'audit.apps.AuditConfig',
    'stockmouvement',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'axes',  # Ajout pour le verrouillage après tentatives échouées
    'debug_toolbar',  # Ajout pour le debug toolbar
]

# Configuration django-axes : verrouillage après 3 tentatives échouées
AXES_FAILURE_LIMIT = 3
AXES_COOLOFF_TIME = 0.09  # 5 minutes de verrouillage
AXES_LOCKOUT_TEMPLATE = None  # Utilise la réponse JSON par défaut pour API


# Use custom user model
AUTH_USER_MODEL = 'user.User'

# Authentification REST
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # utile pour le browsable API
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# API Documentation (drf-spectacular)
SPECTACULAR_SETTINGS = {
    'TITLE': 'SoftCosy API',
    'DESCRIPTION': (
        'REST API for SoftCosy — a sports inventory management system.\n\n'
        '## Authentication\n'
        'All endpoints (except `/api/token/`) require a token.\n'
        'Obtain one via `POST /api/token/` then pass it as:\n'
        '```\nAuthorization: Token <your_token>\n```\n\n'
        '## Modules\n'
        '- **Products** — categories, products, variants (SKU/barcode/pricing)\n'
        '- **Stock** — on-hand quantities, movements, alerts\n'
        '- **Sales** — customers, sales orders, sale lines\n'
        '- **Purchases** — suppliers, purchase orders, purchase lines\n'
        '- **Inventory counts** — physical counts and variance tracking\n'
        '- **Audit** — immutable log of all create/update/delete actions\n'
    ),
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {'name': 'SoftCosy Team'},
    'LICENSE': {'name': 'Proprietary'},
    'ENUM_NAME_OVERRIDES': {
        'SaleStatusEnum': ['PAYE', 'NONPAYE', 'PARTIEL'],
        'InventoryCountStatusEnum': ['ENCOURS', 'FINI'],
    },
    'TAGS': [
        {'name': 'auth', 'description': 'Authentication — obtain and manage tokens'},
        {'name': 'users', 'description': 'User accounts and role management'},
        {'name': 'products', 'description': 'Products, categories, and variants'},
        {'name': 'stock', 'description': 'Stock levels, movements, and alerts'},
        {'name': 'sales', 'description': 'Sales orders, customers, and sale lines'},
        {'name': 'purchases', 'description': 'Purchase orders, suppliers, and purchase lines'},
        {'name': 'inventory-counts', 'description': 'Physical inventory counts and variance tracking'},
        {'name': 'audit', 'description': 'Audit log — read-only, admin only'},
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

# Optionnel : mot de passe plus sécurisé (Argon2 recommandé en 2026)
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.BCryptSHA256PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


MIDDLEWARE = [
    'axes.middleware.AxesMiddleware',  # Ajout du middleware Axes
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',  # Ajout du middleware Debug Toolbar
]

ROOT_URLCONF = 'gestion_softcosy.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gestion_softcosy.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST'),
        'PORT': os.getenv('DB_PORT'),
        'CONN_MAX_AGE': 0,
        'OPTIONS': {
            'sslmode': 'require',
        }
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

INTERNAL_IPS = [
    '127.0.0.1',
]

CORS_ALLOWED_ORIGINS = os.getenv('CORS_ALLOWED_ORIGINS', 'http://localhost:3000,http://localhost:8081').split(',')

# Email (alerts & notifications)
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)
ADMIN_NOTIFY_EMAIL = os.getenv('ADMIN_NOTIFY_EMAIL', EMAIL_HOST_USER)

# Stock movement retention (days)
STOCK_MOVEMENT_RETENTION_DAYS = int(os.getenv('STOCK_MOVEMENT_RETENTION_DAYS', 180))
