# Generated by Django 6.0.2 on 2026-04-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0004_alter_saleline_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, help_text='Nom du client (pour vente rapide)', max_length=255, null=True),
        ),
    ]
