# Generated by Django 6.0.2 on 2026-03-05 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_code_barres_remove_product_code_sku_and_more'),
        ('purchase', '0003_purchaseline_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_lines', to='product.variant'),
        ),
    ]
