# Generated by Django 6.0.2 on 2026-04-19 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditlog',
            old_name='enitity',
            new_name='entity',
        ),
    ]
